name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11
      - name: pip install Django
        run:
          pip3 install --user django
      - name: Run Django unit tests
        run:
          python manage.py test